### ISSUE TITLE
Identity Server 4 1.0.0

### ISSUE THREAD

**Issue by gopijmenon** [Sphiecoh/IdentityServer4.Postgresql#1]
Do you have this working for Identity Server 4 version 1.0.0

**Comment by gopijmenon** [comment]
AddConfigurationStore is not working it gives a error  'IIdentityServerBuilder' does not contain a definition for 'AddConfigurationStore'

**Comment by Sphiecoh** [comment]
I have updated to 1.0.0 and tested from a sample app. Please download 2.0.0 from nuget and test.
If this is not is still not working for you , please give me repro steps.

**Comment by Sphiecoh** [comment]
Also  add .

**Comment by gopijmenon** [comment]
Thanks. By any chance do you have a client sample that does the resource owner password flow?

**Comment by Sphiecoh** [comment]
Please have a look at [samples](https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Clients/src/ConsoleResourceOwnerFlow).
