### ISSUE TITLE
AllowedCorsOrigins gets an error

### ISSUE THREAD

**Issue by Hiroki-Honda** [sphiecoh/IdentityServer4.Postgresql#11]
In the client debug log,
No 'Access-Control-Allow-Origin' header

The code below will fail with an error
CorsPolicyService.cs
---------------------------------------------------------
var origins = await _documentSession.Query<Client>()
.SelectMany(x => x.AllowedCorsOrigins.Select(y => y.Origin))
.ToListAsync().ConfigureAwait(false);
---------------------------------------------------------

AllowedCorsOrigins is now recognized by modifying it as follows.
---------------------------------------------------------
SelectMany(x => x.AllowedCorsOrigins).Select(y => y.Origin)
---------------------------------------------------------
Error Sto

**Comment by sphiecoh** [comment]
Thank you for identifying the issue , I have fixed it and a test for verification.

**Comment by sphiecoh** [comment]
version 2.0.5 pushed to nuget
