### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by gopijmenon** [Sphiecoh/IdentityServer4.Postgresql#2]
Hi:

Can you please provide me some sample data? I am trying to insert data during registration of an user.

Appreciate your help on this.

Thanks,
Gopi

**Comment by Sphiecoh** [comment]
I am not sure what data you looking for ? Please clarify.

**Comment by gopijmenon** [comment]
How would you store a client record to validate against? I am planning to have a registration screen that captures user name and password. Once I do that I want to store it as a client record so that each time a user logs in I should be able to validate against it.

**Comment by Sphiecoh** [comment]
```       
using(var session =   documentStore.LightweightSession(){
var client = new IdentityServer4.Postgresql.Entities.Client
                            {
Id = "ro.client",
                                ClientId ="ro.client",
                                ClientName = "client",
            ClientSecrets = new List<ClientSecret> {new ClientSecret { Value = "secret"}},
                                AllowedGrantTypes =  new List<ClientGrantType> { new ClientGrantType { GrantType = GrantType.Hybrid } , new ClientGrantType {  GrantType = GrantType.ClientCredentials} },
                                AllowedCorsOrigins =  new List<ClientCorsOrigin>  {new ClientCorsOrigin { Origin = "http://localhost:5003" } },
                                RequireClientSecret = false,
                                RequireConsent = false,
                                AllowedScopes = new List<ClientScope>{
                                     new ClientScope { Scope = IdentityServer4.IdentityServerConstants.StandardScopes.OpenId },
                                     new ClientScope { Scope = IdentityServer4.IdentityServerConstants.StandardScopes.Profile },
                                     new ClientScope { Scope ="api1" }
                                },
                                RedirectUris = new List<ClientRedirectUri> { new ClientRedirectUri { RedirectUri ="http://localhost:5003/signin-oidc" } }
                            }

                    session.StoreObjects(client);
                    session.SaveChanges(); 
}
```

This is how you can register the client.

**Comment by gopijmenon** [comment]
Thanks a bunch!

**Comment by gopijmenon** [comment]
What about populating ApiResource and IdentityResource? - Thanks

**Comment by Sphiecoh** [comment]
see [here](https://gist.github.com/Sphiecoh/1464d894df4588c53be8235c7aa7c43d)

**Comment by gopijmenon** [comment]
getting error invalid_scope on token response
var tokenClient = new TokenClient(disco.TokenEndpoint, "ro.client", "secret");
var tokenResponse = await tokenClient.RequestClientCredentialsAsync("api1");

**Comment by Sphiecoh** [comment]
ApiResource needs a scope otherwise it is meaningless, I have added a working [sample](https://github.com/Sphiecoh/IdentityServer4.Postgresql/blob/master/sample/IdentityServer4.Postgresql.Sample/Startup.cs#L57) .

**Comment by gopijmenon** [comment]
if i have to get a refresh token what do I have to do? I am using resource owner password flow.
I added an Scope  new ApiScope { Name = " offline_access", DisplayName = " Offline Access" } } }, to the ApiResources and then added a clientscope
new ClientScope { Scope = IdentityServer4.IdentityServerConstants.StandardScopes.OfflineAccess },
with settings of  AllowOfflineAccess = true, AccessTokenLifetime = 3600, but not getting a refresh token

Thanks
