### ISSUE TITLE
Incorrect query in ResourceStore

### ISSUE THREAD

**Issue by nickvane** [sphiecoh/IdentityServer4.Postgresql#49]
One of the queries in ResourceStore is incorrect:

https://github.com/sphiecoh/IdentityServer4.Postgresql/blob/b7d1d8626a5c3f05fab2879bdfa4b7a27fae0c4e/src/IdentityServer4.Postgresql/Stores/ResourceStore.cs#L30

Should be:

`return Task.FromResult(resources.Where(r => r.Scopes.Any(x => scopeNames.Contains(x.Name))).Select(x => x.ToModel()).AsEnumerable());`

Because it needs to query on the name of the scope and not on the name of the resource.

**Comment by sphiecoh** [comment]
Thank you for raising this , I have  added the change to the latest release
