### ISSUE TITLE
Schema Name in IdentityServerEntityFrameworkBuilderExtensions

### ISSUE THREAD

**Issue by gopijmenon** [Sphiecoh/IdentityServer4.Postgresql#9]
Could you please provide an option to pass the scheme name in the class IdentityServerEntityFrameworkBuilderExtensions for the method AddConfigurationStore like below?

 public static IIdentityServerBuilder AddConfigurationStore(
        this IIdentityServerBuilder builder, string connectionString = null, StoreOptions storeOptions = null)
        {
........

**Comment by Sphiecoh** [comment]
Will [this](https://github.com/Sphiecoh/IdentityServer4.Postgresql/commit/a88b856370fe2e28adabc594537f613e8ee05f45) be sufficient ?

**Comment by Sphiecoh** [comment]
see version 2.0.2
